### ISSUE TITLE
APK DEMO

### ISSUE THREAD

**Issue by Adhaaz** [janjanmedinaaa/watcher-tv#1]
Can I get the APK DEMO, sir?

**Comment by janjanmedinaaa** [comment]
Hi, are you having trouble building the repo? Just a heads up, I don't own the API if you have any problems connecting to it.

Here's a [debug version](https://file.io/5Q35YsheeauG) of the APK since I haven't setup the release APKs yet.

**Comment by Adhaaz** [comment]
Yeah sir

**Comment by janjanmedinaaa** [comment]
Hi, I just released the first version of the App. You can download the APK in the Releases section. Also, I will be closing this issue since it looks like you resolved the issue. Thanks for the support!
