### ISSUE TITLE
App cannot be opened

### ISSUE THREAD

**Issue by Adhaaz** [janjanmedinaaa/watcher-tv#39]
Sir can u Fix this.. I have installed App in my device. Btw, my device is Android 12.. but can't open this app..
![IMG_20230204_063714](https://user-images.githubusercontent.com/75169859/216730549-fe9c4b5f-39e2-457b-8226-5177a75ee97e.jpg)
Please fix it, sir

**Comment by janjanmedinatera** [comment]
Based on the screenshot you installed it on your phone. The app was built and would only work for the Android TV platform since it uses the Android Leanback library.

**Comment by Adhaaz** [comment]
Ouh, okay thank sirrr 👌
